name: neurodetekt
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - black
  - isort
  - tqdm
  - pip:
    - tensorboard
    - rich

